In [1]:
import pandas as pd
from glob import glob
import seaborn as sns
import matplotlib.pyplot as plt
from toolbox import evaluate_combinations

## Leave patients out cross validation (LPOCV)

In [2]:
print("Available files")
glob("results/LPOCV*")

Available files

['results/LPOCV_healthy_vs_cancer_Top 2_Long a+.csv',
 'results/LPOCV_healthy_vs_cancer_Top 2_Long a+ ext..csv',
 'results/LPOCV_healthy_vs_cancer_Top 2_Med. a+ ext..csv',
 'results/LPOCV_healthy_vs_cancer_Top 2_Close skip 1.csv']

In [3]:
class_task = "healthy_vs_cancer"
Fsel = "Top 2"
Msel = "Long a+ ext."

In [4]:
df = pd.read_csv(f"results/LPOCV_{class_task}_{Fsel}_{Msel}.csv")
df.head()

,Architecture,Fold,Random_state,ROC AUC,Recall,F1-score,Mask,Freq. selection,Task
0,SVM,1,0,0.776914,0.707317,0.707317,Long a+ ext.,Top 2,healthy_vs_cancer
1,RF,1,0,0.801435,0.707317,0.706620,Long a+ ext.,Top 2,healthy_vs_cancer
2,Lasso,1,0,0.801435,0.707317,0.707317,Long a+ ext.,Top 2,healthy_vs_cancer
3,SVM,2,0,0.798611,0.764706,0.764706,Long a+ ext.,Top 2,healthy_vs_cancer
4,RF,2,0,0.850694,0.794118,0.793579,Long a+ ext.,Top 2,healthy_vs_cancer

In [5]:
summary = evaluate_combinations(
    df,
    groupby_cols=["Architecture", "Mask", "Task", "Freq. selection"],
    primary_metric="Recall",
)
print("\n\t\t================== Summary table ==================")
print(summary)

		================== Summary table ==================
  Architecture          Mask               Task Freq. selection  ROC AUC_mean  \
0           RF  Long a+ ext.  healthy_vs_cancer           Top 2        0.8478
1        Lasso  Long a+ ext.  healthy_vs_cancer           Top 2        0.8089
2          SVM  Long a+ ext.  healthy_vs_cancer           Top 2        0.7927

   ROC AUC_std  ROC AUC_max  Recall_mean  Recall_std  Recall_max  \
0       0.0675       0.9926       0.7844      0.0667      0.9487
1       0.0702       0.9615       0.7507      0.0733      0.9062
2       0.0679       0.9542       0.7466      0.0581      0.8800

   F1-score_mean  F1-score_std  F1-score_max
0         0.7834        0.0673        0.9487
1         0.7493        0.0742        0.9065
2         0.7450        0.0592        0.8808

# results for 50 random states
plt.figure(figsize=(6, 3))
sns.boxplot(
    data=df,
    x="Fold",
    y="ROC AUC",
    hue="Architecture",
    palette="deep",  # colorblind
)

plt.ylabel("AUC")
plt.xlabel("Folds")
plt.legend(title="Architecture")
plt.grid(True)
plt.tight_layout()
# plt.savefig("results/boxplot_architecture", bbox_inches="tight")
plt.show()

# results for 50 random states
plt.figure(figsize=(6, 3))
sns.boxplot(
    data=df,
    x="Fold",
    y="F1-score",
    hue="Architecture",
    palette="deep",  # colorblind
)

plt.ylabel("F1-score")
plt.xlabel("Folds")
plt.legend(title="Architecture")
plt.grid(True)
plt.tight_layout()
# plt.savefig("results/boxplot_architecture", bbox_inches="tight")
plt.show()

## Leave patients out cross validation (LPOCV) -- combined

In [6]:
import pandas as pd
from pathlib import Path

files = Path("results").glob("LPOCV_*.csv")
combined = pd.concat(
    [pd.read_csv(f).assign(source_file=f.name) for f in files],
    ignore_index=True,
)

In [8]:
combined

,Architecture,Fold,Random_state,ROC AUC,Recall,F1-score,Mask,Freq. selection,Task,source_file
0,SVM,1,0,0.700957,0.682927,0.682927,Long a+,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Long a+.csv
1,RF,1,0,0.765550,0.682927,0.681036,Long a+,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Long a+.csv
2,Lasso,1,0,0.715311,0.682927,0.682165,Long a+,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Long a+.csv
3,SVM,2,0,0.840278,0.794118,0.793579,Long a+,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Long a+.csv
4,RF,2,0,0.857639,0.764706,0.763055,Long a+,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Long a+.csv
...,...,...,...,...,...,...,...,...,...,...
2991,RF,4,49,0.858333,0.815789,0.815404,Close skip 1,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Close skip 1.csv
2992,Lasso,4,49,0.861111,0.763158,0.763322,Close skip 1,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Close skip 1.csv
2993,SVM,5,49,0.841667,0.842105,0.842105,Close skip 1,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Close skip 1.csv
2994,RF,5,49,0.905556,0.815789,0.813842,Close skip 1,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Close skip 1.csv
2995,Lasso,5,49,0.841667,0.815789,0.815404,Close skip 1,Top 2,healthy_vs_cancer,LPOCV_healthy_vs_cancer_Top 2_Close skip 1.csv

In [9]:
summary = evaluate_combinations(
    combined,
    groupby_cols=["Architecture", "Mask", "Task", "Freq. selection"],
    primary_metric="ROC AUC",
)
print("\n\t\t================== Summary table ==================")
print(summary)

		================== Summary table ==================
   Architecture          Mask               Task Freq. selection  \
0            RF  Close skip 1  healthy_vs_cancer           Top 2
1            RF  Med. a+ ext.  healthy_vs_cancer           Top 2
2            RF  Long a+ ext.  healthy_vs_cancer           Top 2
3         Lasso  Close skip 1  healthy_vs_cancer           Top 2
4            RF       Long a+  healthy_vs_cancer           Top 2
5         Lasso  Long a+ ext.  healthy_vs_cancer           Top 2
6           SVM  Med. a+ ext.  healthy_vs_cancer           Top 2
7           SVM  Long a+ ext.  healthy_vs_cancer           Top 2
8         Lasso  Med. a+ ext.  healthy_vs_cancer           Top 2
9         Lasso       Long a+  healthy_vs_cancer           Top 2
10          SVM  Close skip 1  healthy_vs_cancer           Top 2
11          SVM       Long a+  healthy_vs_cancer           Top 2

    ROC AUC_mean  ROC AUC_std  ROC AUC_max  Recall_mean  Recall_std  \
0         0.8703       0.0616       1.0000       0.8041      0.0652
1         0.8494       0.0684       0.9909       0.7997      0.0610
2         0.8478       0.0675       0.9926       0.7844      0.0667
3         0.8423       0.0611       0.9853       0.7699      0.0612
4         0.8310       0.0654       0.9727       0.7584      0.0684
5         0.8089       0.0702       0.9615       0.7507      0.0733
6         0.7995       0.0695       0.9883       0.7324      0.0711
7         0.7927       0.0679       0.9542       0.7466      0.0581
8         0.7859       0.0648       0.9223       0.7307      0.0664
9         0.7829       0.0744       0.9879       0.7267      0.0733
10        0.7630       0.0723       0.9338       0.7127      0.0665
11        0.7450       0.0828       0.9255       0.7074      0.0716

    Recall_max  F1-score_mean  F1-score_std  F1-score_max
0       0.9730         0.8029        0.0662        0.9731
1       0.9730         0.7984        0.0617        0.9731
2       0.9487         0.7834        0.0673        0.9487
3       0.9333         0.7685        0.0618        0.9333
4       0.9032         0.7571        0.0692        0.9032
5       0.9062         0.7493        0.0742        0.9065
6       0.9459         0.7309        0.0720        0.9457
7       0.8800         0.7450        0.0592        0.8808
8       0.9000         0.7292        0.0675        0.8985
9       0.9512         0.7244        0.0747        0.9514
10      0.8571         0.7108        0.0671        0.8569
11      0.8780         0.7054        0.0727        0.8776